version: '3.8'

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    command: ["echo", "Hello from PgAdmin"]
    env_file:
      - ./.env
    ports:
      - "5050:80"
    restart: always

volumes:
  postgres_data: