# Generated by Django 5.0.1 on 2024-06-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameuser',
            name='memory_multi_player',
        ),
        migrations.RemoveField(
            model_name='gameuser',
            name='memory_single_player',
        ),
        migrations.RemoveField(
            model_name='gameuser',
            name='pong_multi_player',
        ),
        migrations.RemoveField(
            model_name='gameuser',
            name='pong_single_player',
        ),
        migrations.DeleteModel(
            name='GameStats',
        ),
        migrations.DeleteModel(
            name='GameUser',
        ),
    ]
