
const defaults = {
    USERNAME_MIN_LENGTH: 2,
    USERNAME_MAX_LENGTH: 20,
    EMAIL_MIN_LENGTH: 2,
    EMAIL_MAX_LENGTH: 50,
    ALIAS_MIN_LENGTH: 2,
    ALIAS_MAX_LENGTH: 15,
    AI_USERNAME: 'AI',
    MEMORY_SINGLE_TIME: 12,
}

export default defaults;