# Generated by Django 4.2.13 on 2024-05-29 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='memory_multi_player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_multi_player', to='app.gamestats'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='memory_single_player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_single_player', to='app.gamestats'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='pong_multi_player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pong_multi_player', to='app.gamestats'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='pong_single_player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pong_single_player', to='app.gamestats'),
        ),
    ]
