# Generated by Django 4.2.13 on 2024-05-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_gameuser_memory_multi_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
